name: Build and push ipcc
on:
  workflow_dispatch
env:
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
  IMAGE_NAME: ip-location-service-bsky

jobs:
  build-and-push-ipcc:
    if: github.repository == 'inconceivableza/ip-location-api'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long

      - name: Build and push Docker image
        id: build-and-push
        run: |
          DOCKER_FLAGS=(--platform=linux/amd64,linux/arm64,--cache-from=type=gha,--cache-to=type=gha,mode=max)
          while IFS= read -r label; do
            plain_label="$(echo "${label}" | sed 's/^ *\(.*\) *$/\1/' | grep -v "'")"
            [ "$plain_label" != "" ] && DOCKER_FLAGS+=(--label "${plain_label}")
          done <<< "${{ steps.meta.outputs.labels }}"
          while IFS= read -r tag; do
            plain_tag="$(echo "${tag}" | sed 's/^ *\(.*\) *$/\1/' | grep -v "'")"
            [ "$plain_tag" != "" ] && DOCKER_FLAGS+=(--tag "${plain_tag}")
          done <<< "${{ steps.meta.outputs.tags }}"
          echo "docker buildx build ${DOCKER_FLAGS[@]} ."
          docker buildx build "${DOCKER_FLAGS[@]}" .

